name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer

jobs:
  swift:
    name: Swift
    runs-on: macos-13
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Build
      run: swift build -v -Xswiftc -warnings-as-errors
    - name: Test
      run: swift test -v
